apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tenant-tls
  namespace: minio-tenant
spec:
  secretName: minio-tenant-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - minio-console.chingadero.com
