apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-tenant
  namespace: minio-tenant
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - minio-console.chingadero.com
      secretName: minio-tenant-tls
  rules:
    - host: minio-console.chingadero.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-tenant-console
                port:
                  number: 9090
