apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mini
  namespace: kube-system
  annotations:
    lbipam.cilium.io/sharing-key: "shared-lb"
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - minio.chingadero.com
      secretName: minio-api-tls
  rules:
    - host: minio.chingadero.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 80
