# /etc/rancher/rke2/config.yaml
---
node-name: "rke1.chingadero.com"
node-ip: "10.10.10.1"
advertise-address: "10.10.10.1"
node-external-ip: "69.169.96.210"
cluster-cidr: "10.42.0.0/16"
service-cidr: "10.43.0.0/16"
cni: "none"
disable-kube-proxy: true
disable:
- "rke2-ingress-nginx"
tls-san:
- "rke1.chingadero.com"
- "localhost"
- "69.169.96.210"
- "10.10.10.1"
- "127.0.0.1"
write-kubeconfig-mode: "0644"
roles:
- "controlplane"
- "etcd"
- "worker"
cluster-domain: "chingadero.com"
