#server: "https://rke.chingadero.com:9345"
token: ""
node-name: ""
cluster-cidr: "10.42.0.0/16"
service-cidr: "10.43.0.0/16"
cni: "none"
disable-kube-proxy: true
disable:
- "rke2-ingress-nginx"
tls-san:
- "rke.chingadero.com"
- "rke1.chingadero.com"
- "rke2.chingadero.com"
- "rke3.chingadero.com"
- "localhost"
- "127.0.0.1"
write-kubeconfig-mode: "0644"
roles:
- "controlplane"
- "etcd"
- "worker"
cluster-domain: "cluster.local"
