# ### https://github.com/minio/operator/blob/master/helm/operator/values.yaml ###
# # Root key for Operator Helm Chart
operator:
  # See `Operator environment variables <https://github.com/minio/operator/blob/master/docs/env-variables.md>`__ for a list of all supported values.
  env:
    - name: OPERATOR_STS_ENABLED
      value: "on"
    - name: MINIO_OPERATOR_RUNTIME
      value: "Rancher"
  image:
    repository: quay.io/minio/operator
    tag: v7.1.1
    pullPolicy: IfNotPresent
  installCRDs: true