default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

development:
  <<: *default
  database: gemini_chat_development

test:
  <<: *default
  database: gemini_chat_test

production:
  <<: *default
  database: gemini_chat_production
  username: gemini_chat
  password: <%= ENV["GEMINI_CHAT_DATABASE_PASSWORD"] %>