default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "dummy_password") %>

development:
  <<: *default
  database: gemini_chat_development

test:
  <<: *default
  database: gemini_chat_test

production:
  primary:
    <<: *default
    database: chingadero_chat_production
  cable:
    <<: *default
    database: chingadero_chat_cable_production
    migrations_paths: db/cable_migrate
  queue:
    <<: *default
    database: chingadero_chat_queue_production
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: chingadero_chat_cache_production
    migrations_paths: db/cache_migrate