apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn.local-tls
  namespace: longhorn-system
spec:
  secretName: longhorn.local-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  dnsNames:
    - longhorn.chingadero.com
