kubeProxyReplacement: true
k8sServiceHost: 127.0.0.1
k8sServicePort: '6443'
ingressController:
  enabled: true
  default: true
  metadata:
    name: cilium-ingress-lb
    namespace: kube-system
    annotations:
      service.beta.kubernetes.io/cilium-loadbalancer-ip: "72.47.146.48"
  service:
    type: LoadBalancer
    LoadBalancerIP: "72.47.146.48"
operator:
  replicas: 1
hubble:
  relay:
    enabled: true
    replicas: 1
  ui:
    enabled: true
    replicas: 1
<<<<<<< HEAD
=======
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - 72.47.146.0/24
>>>>>>> 76b6573 (Cleaning up)
gatewayAPI:
  enabled: true
l2announcements:
  enabled: true
