apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-api
  namespace: kube-system
spec:
  ingressClassName: cilium
  rules:
  - http:
      paths:
      - backend:
          service:
            name: minio-tenant-console
            port:
              number: 9443
        path: /console
        pathType: Prefix
      - backend:
          service:
            name: minio
            port:
              number: 443
        path: /minio
        pathType: Prefix

